/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Core.GenerateQuestion;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import util2.TestQuestion;
import util2.TimeRestriction;

/**
 *
 * @author nikola.panajotovic
 * @author nikola.bijelic
 */
public class QuestionsPage extends javax.swing.JPanel {
    
    private List<TestQuestion> questions;
    private static int MINUTES = 60;
    private int candidateId;
    private int numberOfQuestions;
    private int testDuration;
    
    private JFrame root;

    private TimeRestriction restriction;
    /**
     * Creates new form QuestionsPage
     */
    public QuestionsPage(int numberOfQuestions, int testDuration, int candidateId) throws Exception {
        this.numberOfQuestions = numberOfQuestions;
        this.testDuration = testDuration * MINUTES;
        this.candidateId = candidateId;
        initComponents();
        TimeRestriction.TESTDURATION = this.testDuration;
        restriction = new TimeRestriction(timeBar);
        initQuestionPanel(this.candidateId, this.numberOfQuestions);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endBtn = new javax.swing.JButton();
        timeBar = new javax.swing.JProgressBar();
        timeLabel = new javax.swing.JLabel();
        tabPanelQuestions = new javax.swing.JTabbedPane();

        endBtn.setText("End Test");
        endBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endBtnActionPerformed(evt);
            }
        });

        timeBar.setMaximum(30);
        timeBar.setStringPainted(true);

        timeLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeLabel.setText("Remaining Time");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPanelQuestions)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(timeBar, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanelQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(timeBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void endBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endBtnActionPerformed
        restriction.startTime();
    }//GEN-LAST:event_endBtnActionPerformed

    public void setParent(JFrame frame){
        root = frame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endBtn;
    private javax.swing.JTabbedPane tabPanelQuestions;
    private javax.swing.JProgressBar timeBar;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables

    private void initQuestionPanel(int candidateId, int numberOfQuestions) throws Exception {
        GenerateQuestion.getQuestions(candidateId, numberOfQuestions);
        questions = GenerateQuestion.getList();
        int numQuestions = questions.size();
        for(int i = 0; i < numQuestions; i++){
            tabPanelQuestions.addTab("Question " + (i + 1), new JPanel());
        }
    }

}
